[env:HELTEC_LORA_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

; Serial Configuration
monitor_speed = 115200
monitor_port = /dev/ttyUSB0

upload_speed = 921600
upload_port = /dev/ttyUSB0

build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_LOGLEVEL=0

; Library Dependencies
lib_deps = 
    SPI
    SD
	FS

monitor_filters = esp32_exception_decoder

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
