[env:HELTEC_WIFI_LORA_32_V3]
platform = espressif32@^6.0.0
board = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed = 115200

; Build options
; build_flags = 

; Required libraries
lib_deps = 
    SD
; Optional: If you need specific versions
; lib_deps =
;     espressif/esp-idf-lib @ ^0.10.0
;     https://github.com/espressif/arduino-esp32.git



